#pragma once

enum SOUND_TYPE {
	SOUND_TYPE_STAGE,
	SOUND_TYPE_BALL,
	SOUND_TYPE_HIT,
	SOUND_TYPE_DAMAGE_P,
	SOUND_TYPE_DAMAGE_E,
	SOUND_TYPE_DIE,
	SOUND_TYPE_REVIVE,
	SOUND_TYPE_WALK,
	SOUND_TYPE_JUMP,
	SOUND_TYPE_ICEBALL,
	SOUND_TYPE_POISON,
	SOUND_TYPE_WALLIMPACT,
	SOUND_TYPE_MOVEMENT,
	SOUND_TYPE_CHARGE,
	SOUND_TYPE_ARROW,
	SOUND_TYPE_SLASH,
	SOUND_TYPE_BOSSEN1,
	SOUND_TYPE_BOSSEN2,
	SOUND_TYPE_BOSSDE1,
	SOUND_TYPE_BOSSDE2,
	SOUND_TYPE_SHIELD,
	SOUND_TYPE_SHIELDH,
	SOUND_TYPE_BEBOSS,
	SOUND_TYPE_BOSS,
	SOUND_TYPE_ENDING,
	SOUND_TYPE_FIREBALL,
	SOUND_TYPE_MAX
};

void SoundSysInit(void);
void SoundGameInit(void);
void SoundControl(void);
void PlaySoundType(SOUND_TYPE id);
void StopSoundType(SOUND_TYPE id);
void StopAllSound(void);